# Generated by Django 3.2.11 on 2022-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('authorbio', models.TextField(max_length=2000)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
