# Generated by Django 3.2.11 on 2022-01-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('author_bio', models.TextField()),
                ('content', models.TextField()),
                ('post_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
