# Generated by Django 3.2.11 on 2022-01-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_posts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author_bio',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author_name',
        ),
    ]
