# Generated by Django 3.2.11 on 2022-01-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_posts_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('authorname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
