# Generated by Django 3.2.11 on 2022-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_auto_20220126_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author_name',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
